### Rota para cadastrar a bicicleta
POST http://localhost:3000/bicycle
Content-Type: application/json

{
  "color":"Blue",
  "gears": 20,
  "brand": "Caloi",
  "model":"Trial",
  "price": 1500
}

###  Rota para listar todas as bicicletas que ainda nao foram vendidas
GET http://localhost:3000/bicycles

### Rota para filtrar por cor
GET http://localhost:3000/bicycles/color/blue

### Rota para filtrar as bicicletas até o preço desejado  
PUT http://localhost:3000/bicycles/price
Content-Type: application/json

{ 
  "price": 1000
}

### Rota para alterar o preço de uma bicicleta
PUT  http://localhost:3000/bicycles/update/
Content-Type: application/json

{ 
  "id":"033f9a47-a8c0-4a85-8444-80d70fb9637f",
  "price": 30000
}

### Rota para vender uma bicicleta
PUT  http://localhost:3000/bicycles/sell/
Content-Type: application/json

{ 
  "id":"c111fe8a-356e-41d4-957d-2fef36f12ae4"
}

### Rota para listar todas as bicicletas vendidas
GET http://localhost:3000/bicycles/sold/
