### Create bicycle
POST http://localhost:3000/bicycle
Content-Type: application/json

{
  "color":"vermelho",
  "gears": 20,
  "brand": "",
  "model":"dasd",
  "price": 55500
}

###
GET http://localhost:3000/bicycles

###
GET http://localhost:3000/bicycles/color/azul

###
GET http://localhost:3000/bicycles/price/30000

###
PUT  http://localhost:3000/bicycles/update/cf48dc61-7e9e-4903-8f08-1085c6d563c4
Content-Type: application/json

{ 
  "price": 300000
}